language: php

branches:
    only:
    - master

services: 
    - mysql
php:
    - 7.2
    - 7.3

before_install:
    - mysql -e "CREATE DATABASE sofadb CHARACTER SET utf8;"
    - mysql -u root --password="" sofadb < sql/sofadb.sql
    - mysql -u root --password="" sofadb < sql/input_types.sql
    - mysql -u root --password="" sofadb < sql/method_info_options.sql
    - mysql -u root --password="" sofadb < sql/method_info_reference_list.sql
    - mysql -u root --password="" sofadb < sql/method_info_types.sql
    - mysql -u root --password="" sofadb < sql/method_infos.sql
    - mysql -u root --password="" sofadb < sql/methods.sql
    - mysql -u root --password="" sofadb < sql/prompts.sql
    - mysql -u root --password="" sofadb < sql/reference.sql

install:
    - composer install --no-interaction

script:
    - if find . -name "*.php" ! -path "./vendor/*" -exec php -l {} 2>&1 \; | grep "syntax error, unexpected"; then exit 1; fi