ALTER TABLE cases MODIFY COLUMN idage_notes VARCHAR(255) DEFAULT "";
ALTER TABLE cases MODIFY COLUMN idsex_notes VARCHAR(255) DEFAULT "";
ALTER TABLE cases MODIFY COLUMN faage_notes VARCHAR(255) DEFAULT "";
ALTER TABLE cases MODIFY COLUMN idstature_notes VARCHAR(255) DEFAULT "";

